# src/Blogger/BlogBundle/Resources/config/config.yml
parameters:
    # Blogger contact email address
    blogger_blog.emails.contact_email: cheynede@gmail.com
    blogger_blog.emails.admin_email: cheynede@gmail.com
    blogger_blog.comments.latest_comment_limit: 10